---
- hosts: ansible_node
  become: yes
  gather_facts: yes
  tasks:
    - name: Gather facts # Использовала для дебага
      setup:
    - name: Установка nginx
      apt:
        name: nginx
        state: latest
    - name: Запуск nginx
      service:
        name: nginx
        state: started

    - name: Настроить Nginx как прокси-сервер для FastAPI
      copy:
        content: |
          server {
            listen 80;
            server_name 172.17.0.2;

            location / {
              proxy_pass http://127.0.0.1:8000;
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto $scheme;

            }
          }
        dest: /etc/nginx/sites-available/fastapi
        mode: "0644"
    - name: Включить конфигурацию Nginx для FastAPI
      file:
        src: /etc/nginx/sites-available/fastapi
        dest: /etc/nginx/sites-enabled/fastapi
        state: link

    - name: Перезапустить Nginx для применения конфигурации
      service:
        name: nginx
        state: restarted

